name: Bug report
description: Report a problem in Valley of Bitumen
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen?
      placeholder: Clear description of the bug.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      placeholder: "1) ... 2) ... 3) ..."
  - type: input
    id: version
    attributes:
      label: Game version / commit
      placeholder: e.g. v0.1.0 or abc123
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Windows
        - macOS
        - Linux
        - Steam Deck
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
